apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/
  - infrastructure/cert-manager/
  - infrastructure/cluster-issuer/
  - apps/backend/
  - apps/frontend/
  - apps/redis/
  - ingress/